# Generated by Django 4.2.7 on 2023-12-26 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_alter_employee_dept_alter_employee_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
